### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [liks79/sample-saga-with-aws-step-functions#1]
Error occured on `pip install -r monolithic/requiremens.txt'.
My environment is 

- OS X
- venv
- python 3.7.6

Error log is below

Collecting psycopg2==2.8.4 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 913kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f9/5ykq8zsx60nfvp5q520dn0180000gp/T/pip-install-i4807fko/psycopg2/
(venv)  ✘ ys@smartui-MacBook-Pro  ~/dev/sample-saga-with-aws-step-functions/monolithic   master 

**Comment by liks79** [comment]
You can uncomment it.
It is not mandatory package.
It will be removed next commit.
Thanks a lot.
