### ISSUE TITLE
Error occured on `python monolithic/data_generator.py`

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [liks79/sample-saga-with-aws-step-functions#2]
Error occured on `python monolithic/data_generator.py`
Log is below

Traceback (most recent call last):
  File "data_generator.py", line 15, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by liks79** [comment]
You can run 'pip install -r requirements.txt' before run data_generator.py
